# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Rob Hoffmann
tagline: Front-end engineer, PHP developer, New York Mets fan.
author :
  name : Rob Hoffmann
  email : rhoffmann8@gmail.com
  github : rhoffmann8
  twitter : rhoffmann8
  gplus : 106157659251612844689
  #feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://rhoffmann8.github.io

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : false

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    #provider : disqus
    provider : false
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
   
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-64538863-1'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  # Settings for sharing helper. 
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
excerpt_separator: <!--more-->

sass:
  sass_dir: _sass

stadiums:
  - {name: Angel Stadium of Anaheim, visited: false}
  - {name: AT&T Park, visited: false}
  - {name: Busch Stadium, visited: false}
  - {name: Chase Field, visited: false}
  - {name: Citi Field, visited: true}
  - {name: Citizens Bank Park, visited: false}
  - {name: Comerica Park, visited: false}
  - {name: Coors Field, visited: false}
  - {name: Dodger Stadium, visited: false}
  - {name: Fenway Park, visited: false}
  - {name: Globe Life Park in Arlington, visited: false}
  - {name: Great American Ball Park, visited: false}
  - {name: Kauffman Stadium, visited: false}
  - {name: Marlins Park, visited: false}
  - {name: Miller Park, visited: false}
  - {name: Minute Maid Park, visited: false}
  - {name: Nationals Park, visited: false}
  - {name: O.co Coliseum, visited: false}
  - {name: Oriole Park at Camden Yards, visited: false}
  - {name: Petco Park, visited: false}
  - {name: PNC Park, visited: false}
  - {name: Progressive Field, visited: false}
  - {name: Rogers Centre, visited: false}
  - {name: Safeco Field, visited: false}
  - {name: Target Field, visited: false}
  - {name: Tropicana Field, visited: false}
  - {name: Turner Field, visited: true}
  - {name: U.S. Cellular Field, visited: false}
  - {name: Wrigley Field, visited: false}
  - {name: Yankee Stadium, visited: false}